<nav>
  <div class="nav-inner">
    <ul>
      <li><a href="/students/droussy1/finalproject/protosite/index.html">Home</a></li>
      <li><a href="/students/droussy1/finalproject/protosite/about/index.html">About</a></li>
      <li><a href="/students/droussy1/finalproject/protosite/lectures/index.html">Lectures</a></li>
      <li><a href="/students/droussy1/finalproject/protosite/exercises/index.html">Exercies</a></li>
      <li><a href="/students/droussy1/finalproject/protosite/quizzes/index.html">Quizzes</a></li>
    </ul>
  </div>
</nav> 